// Banque de mots en français pour le jeu de dessin
module.exports = [
  "chat", "chien", "maison", "arbre", "soleil", "lune", "étoile", "voiture",
  "vélo", "avion", "bateau", "train", "fleur", "montagne", "plage", "océan",
  "rivière", "pont", "château", "église", "école", "hôpital", "restaurant",
  "pizza", "hamburger", "gâteau", "glace", "café", "thé", "pomme", "banane",
  "fraise", "raisin", "citron", "orange", "ananas", "pastèque", "carotte",
  "tomate", "pomme de terre", "champignon", "poisson", "requin", "baleine",
  "dauphin", "poulpe", "crabe", "tortue", "grenouille", "serpent", "lion",
  "tigre", "éléphant", "girafe", "singe", "ours", "renard", "loup", "lapin",
  "écureuil", "hérisson", "souris", "cheval", "vache", "cochon", "mouton",
  "poule", "coq", "canard", "oie", "aigle", "hibou", "perroquet", "papillon",
  "abeille", "araignée", "fourmi", "coccinelle", "escargot", "dragon",
  "licorne", "fantôme", "sorcière", "vampire", "zombie", "robot",
  "extraterrestre", "astronaute", "fusée", "planète", "arc-en-ciel", "nuage",
  "pluie", "neige", "orage", "éclair", "feu", "glace", "eau", "vent",
  "guitare", "piano", "violon", "batterie", "trompette", "microphone",
  "téléphone", "ordinateur", "télévision", "appareil photo", "livre",
  "crayon", "stylo", "ciseaux", "parapluie", "lunettes", "chapeau",
  "chaussure", "chaussette", "t-shirt", "pantalon", "robe", "montre",
  "horloge", "clé", "porte", "fenêtre", "chaise", "table", "lit", "lampe",
  "miroir", "bougie", "cadeau", "ballon", "drapeau", "coeur", "couronne",
  "épée", "bouclier", "flèche", "arc", "bombe", "aimant", "échelle",
  "roue", "ancre", "boussole", "carte", "globe", "valise", "sac à dos",
  "brosse à dents", "savon", "serviette", "douche", "baignoire",
  "réfrigérateur", "four", "micro-ondes", "grille-pain", "cafetière",
  "aspirateur", "balai", "seau", "marteau", "tournevis", "scie", "clou",
  "vis", "échelle", "pinceau", "peinture", "puzzle", "dé", "cartes à jouer",
  "échecs", "footballeur", "basketball", "tennis", "natation", "ski",
  "surf", "escalade", "danse", "yoga", "clown", "magicien", "pirate",
  "chevalier", "roi", "reine", "prince", "princesse", "cowboy", "policier",
  "pompier", "médecin", "infirmier", "professeur", "chef cuisinier",
  "musicien", "peintre", "photographe", "scientifique", "astronaute",
  "pyramide", "tour Eiffel", "statue de la Liberté", "grande muraille",
  "volcan", "désert", "forêt", "jungle", "île", "cascade", "grotte",
  "iceberg", "aurore boréale", "tornade", "tsunami", "tremblement de terre",
  "sablier", "bougie d'anniversaire", "confettis", "feu d'artifice",
  "guirlande", "sapin de Noël", "citrouille", "oeuf de Pâques", "cadeaux",
  "carrousel", "montagnes russes", "grande roue", "trampoline", "toboggan",
  "balançoire", "cerf-volant", "bulle de savon", "toupie", "yo-yo",
  "marionnette", "peluche", "poupée", "robot jouet", "lego", "puzzle",
];
